#!/usr/bin/env bash
set -xeu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
CWD=$PWD
PACKAGE="sabertooth-py-setup"
ZFEC="zfec-1.5.5.1.zip"

tmpdir="$TMPDIR/$PACKAGE"
mkdir -p "$tmpdir"

# build installer
cat "$CWD/install.in" > "$CWD/install"

# download packages
curl -C - -o - "https://github.com/nsat/zfec/releases/download/release-zfec-1.5.5.1/zfec-1.5.5.1.zip" >> "$CWD/install"

echo package created at $CWD/install

exit 0
