pages:
  - index
  - Fundamentals
  - GettingStarted
  - ExecutionEnvironment
  - AttitudeControl
  - Utilities
  - Tutorials
  - FAQ
  - tutorials/hello_world/index
  - tutorials/rf_collect/index
  - tutorials/rf_transmit/index
  - tutorials/aoi/index
  - tutorials/isl/index
  - tutorials/ipc/index
  - tutorials/data_xfr/index
  - dev-env/in-orbit/index
images:
  - images/**/*
  - text/**/*  # A little hacky to put this under images, but works for any static file
