pages:
  - index
  - Fundamentals
  - GettingStarted
  - ExecutionEnvironment
  - AttitudeControl
  - Utilities
  - FAQ
  - PayloadInSpace
  - tutorials/adcs-lease/index
  - tutorials/aoi/index
  - tutorials/cuda/index
  - tutorials/cudnn/index
  - tutorials/data_xfr/index
  - tutorials/hello_world/index
  - tutorials/index
  - tutorials/ipc/index
  - tutorials/isl/index
  - tutorials/rf_collect/index
  - tutorials/rf_transmit/index
  - tutorials/payload_in_space/download_file/index
  - dev-env/index
  - dev-env/cross-compiling/index
  - dev-env/in-orbit/index
  # - dev-env/sabertooth/index
  - dev-env/vm/index
images:
  - images/**/*
  - text/**/*  # A little hacky to put this under images, but works for any static file
  - tutorials/adcs-lease/adcs_data.json
