#!/usr/bin/env bash
set -xe

########################################
#
# Deploy and run fr_collect demo
#
# Usage:
#
#    deploy <AUTH_TOKEN> <SAT_ID>
#
########################################

AUTH_HEADER="Authorization: Bearer $1"
SAT_ID="$2"
START=$(( `date -u +'%s'` + 86400 ))

HOST="https://api.orb.spire.com"

SATELLITE_ID="satellite_id=${SAT_ID}"
PAYLOAD="payload=SDR"
DESTINATION_PATH="destination_path=/persist/bin/rf_collect_demo"
EXECUTABLE="executable=true"
QUERY_PARAMS="${SATELLITE_ID}&${PAYLOAD}&${DESTINATION_PATH}&${EXECUTABLE}"

curl -X POST ${HOST}/tasking/upload?${QUERY_PARAMS} \
-H "${AUTH_HEADER}"  \
-F "file=@rf_collect_demo"



curl -X POST ${HOST}/tasking/window \
-H "${AUTH_HEADER}" \
-H "Content-Type: application/json" \
-d @- << EOF
{
    "type": "PAYLOAD_SDR",
    "satellite_id": "${SAT_ID}",
    "start": ${START},
    "duration": 60,
    "parameters": {
        "user_command": {
            "executable": "/persist/bin/entry.sh",
            "executable_arguments": ["/persist/bin/rf_collect_demo"]
        }
    }
}
EOF

echo "Done."