
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-26T18:42:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "75a5dcf1cd32374a5f2b7153906d1fa425f20a0e",
 "version": "3.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
