#!/usr/bin/env bash

set -xe

# verify CUDA env
/usr/local/cuda-10.0/bin/nvcc -V

mkdir -p /persist/samples/

/usr/local/cuda-10.0/bin/cuda-install-samples-10.0.sh /persist/samples/

ls -la /persist/*

SAMPLES_ROOT=/persist/samples/NVIDIA_CUDA-10.0_Samples

trap "rm -rf $SAMPLES_ROOT" EXIT

# build and run some samples
(   cd $SAMPLES_ROOT/1_Utilities/deviceQuery &&
    make -j 4 &&
    ./deviceQuery
)
(   cd $SAMPLES_ROOT/1_Utilities/bandwidthTest &&
    make -j 4 &&
    ./bandwidthTest
)
(   cd $SAMPLES_ROOT/6_Advanced/transpose &&
    make -j 4 &&
    ./transpose
)
