
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-04T15:55:12-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "05a4a511a2096d2a7aad8d165bdc6657c8c3d093",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
